/**
 * Mandi Pulse - Reference Market Snapshot & Fallback Provider
 * Synchronized automatically from SQLite Warehouse (v_live_mandi_prices).
 * Generated at: 2026-09-25 12:09:22
 */

export const METRO_HUBS = [
  {
    "id": "delhi",
    "name": "Delhi NCR",
    "terminal_mandi": "Azadpur APMC",
    "district": "North Delhi",
    "lgd_code": 93
  },
  {
    "id": "mumbai",
    "name": "Mumbai MMR",
    "terminal_mandi": "Vashi (Navi Mumbai)",
    "district": "Thane",
    "lgd_code": 499
  },
  {
    "id": "bengaluru",
    "name": "Bengaluru",
    "terminal_mandi": "Yeshwanthpur APMC",
    "district": "Bengaluru Urban",
    "lgd_code": 529
  },
  {
    "id": "kolkata",
    "name": "Kolkata",
    "terminal_mandi": "Mechua Fruit & Veg Market",
    "district": "Kolkata",
    "lgd_code": 318
  },
  {
    "id": "pune",
    "name": "Pune",
    "terminal_mandi": "Gultekdi Market Yard",
    "district": "Pune",
    "lgd_code": 490
  }
];

export const REFERENCE_MARKET_DATA = {
  "delhi": {
    "metro_name": "Delhi NCR",
    "reporting_date": "21 Sep 2026",
    "terminal_mandi": "Azadpur APMC",
    "basket_hero": {
      "weekly_total_rs": 183.9,
      "week_change_pct": 10.8,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Madanapalle)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 2319.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 31.3,
        "day_change_rs": 0.0,
        "week_change_pct": -16.6,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Madanapalle stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 464,
        "retail_box_equivalent_rs": 626,
        "bulk_savings_rs": 162,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 21.25,
          "transit_fee_rs_kg": 3.75,
          "retail_margin_rs_kg": 5.84,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.464,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Madanapalle",
          "distance_km": 400,
          "arrival_z_score": -9.876,
          "weather_context": "Monsoon transitions across Madanapalle agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 2800.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 38.1,
        "day_change_rs": 7.0,
        "week_change_pct": -3.5,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Lasalgaon steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1400,
        "retail_box_equivalent_rs": 1905,
        "bulk_savings_rs": 505,
        "bulk_savings_pct": 26.5,
        "rupee_journey": {
          "farmgate_rs_kg": 34.0,
          "transit_fee_rs_kg": 6.0,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.56,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": -13.682,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 2850.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 38.2,
        "day_change_rs": -1.5,
        "week_change_pct": 38.7,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 4.1\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1425,
        "retail_box_equivalent_rs": 1910,
        "bulk_savings_rs": 485,
        "bulk_savings_pct": 25.4,
        "rupee_journey": {
          "farmgate_rs_kg": 4.25,
          "transit_fee_rs_kg": 0.75,
          "retail_margin_rs_kg": 32.63,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.57,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": -4.119,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "mumbai": {
    "metro_name": "Mumbai MMR",
    "reporting_date": "25 Sep 2026",
    "terminal_mandi": "Vashi (Navi Mumbai)",
    "basket_hero": {
      "weekly_total_rs": 193.93,
      "week_change_pct": -28.1,
      "verdict": "Stable arrivals across primary Mandis keep the Mumbai MMR kitchen basket balanced.",
      "verdict_status": "fair",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 1250.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 39.5,
        "day_change_rs": -5.0,
        "week_change_pct": 25.0,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Kolar arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 250,
        "retail_box_equivalent_rs": 790,
        "bulk_savings_rs": 540,
        "bulk_savings_pct": 68.4,
        "rupee_journey": {
          "farmgate_rs_kg": 10.62,
          "transit_fee_rs_kg": 1.88,
          "retail_margin_rs_kg": 26.88,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.131,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 750.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 54.4,
        "day_change_rs": -44.5,
        "week_change_pct": -82.8,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Lasalgaon stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 375,
        "retail_box_equivalent_rs": 2719,
        "bulk_savings_rs": 2344,
        "bulk_savings_pct": 86.2,
        "rupee_journey": {
          "farmgate_rs_kg": 6.38,
          "transit_fee_rs_kg": 1.12,
          "retail_margin_rs_kg": 46.8,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.079,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 1650.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 22.8,
        "day_change_rs": -7.0,
        "week_change_pct": 0.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Farrukhabad steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 825,
        "retail_box_equivalent_rs": 1142,
        "bulk_savings_rs": 317,
        "bulk_savings_pct": 27.8,
        "rupee_journey": {
          "farmgate_rs_kg": 14.03,
          "transit_fee_rs_kg": 2.48,
          "retail_margin_rs_kg": 6.16,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.173,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "bengaluru": {
    "metro_name": "Bengaluru",
    "reporting_date": "25 Sep 2026",
    "terminal_mandi": "Yeshwanthpur APMC",
    "basket_hero": {
      "weekly_total_rs": 183.42,
      "week_change_pct": 30.6,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 2234.1,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 29.0,
        "day_change_rs": 0.23,
        "week_change_pct": 1.2,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Kolar steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 447,
        "retail_box_equivalent_rs": 580,
        "bulk_savings_rs": 133,
        "bulk_savings_pct": 22.9,
        "rupee_journey": {
          "farmgate_rs_kg": 41.65,
          "transit_fee_rs_kg": 7.35,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.335,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": -4.161,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 4400.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 54.4,
        "day_change_rs": 0.0,
        "week_change_pct": 76.0,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Lasalgaon arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2200,
        "retail_box_equivalent_rs": 2719,
        "bulk_savings_rs": 519,
        "bulk_savings_pct": 19.1,
        "rupee_journey": {
          "farmgate_rs_kg": 37.4,
          "transit_fee_rs_kg": 6.6,
          "retail_margin_rs_kg": 9.72,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.66,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 2000.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 22.8,
        "day_change_rs": 0.0,
        "week_change_pct": 0.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Farrukhabad steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1000,
        "retail_box_equivalent_rs": 1142,
        "bulk_savings_rs": 142,
        "bulk_savings_pct": 12.4,
        "rupee_journey": {
          "farmgate_rs_kg": 17.0,
          "transit_fee_rs_kg": 3.0,
          "retail_margin_rs_kg": 2.53,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.3,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "kolkata": {
    "metro_name": "Kolkata",
    "reporting_date": "25 Sep 2026",
    "terminal_mandi": "Mechua Fruit & Veg Market",
    "basket_hero": {
      "weekly_total_rs": 193.93,
      "week_change_pct": 12.1,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 4400.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 39.5,
        "day_change_rs": 20.0,
        "week_change_pct": 37.5,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Kolar arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 880,
        "retail_box_equivalent_rs": 790,
        "bulk_savings_rs": 0,
        "bulk_savings_pct": 0.0,
        "rupee_journey": {
          "farmgate_rs_kg": 37.4,
          "transit_fee_rs_kg": 6.6,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.44,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 3400.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 54.4,
        "day_change_rs": -20.0,
        "week_change_pct": -34.6,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Lasalgaon stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1700,
        "retail_box_equivalent_rs": 2719,
        "bulk_savings_rs": 1019,
        "bulk_savings_pct": 37.5,
        "rupee_journey": {
          "farmgate_rs_kg": 28.9,
          "transit_fee_rs_kg": 5.1,
          "retail_margin_rs_kg": 20.04,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.34,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 3800.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 22.8,
        "day_change_rs": 13.0,
        "week_change_pct": 46.1,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1900,
        "retail_box_equivalent_rs": 1142,
        "bulk_savings_rs": 0,
        "bulk_savings_pct": 0.0,
        "rupee_journey": {
          "farmgate_rs_kg": 32.3,
          "transit_fee_rs_kg": 5.7,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.38,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "pune": {
    "metro_name": "Pune",
    "reporting_date": "25 Sep 2026",
    "terminal_mandi": "Gultekdi Market Yard",
    "basket_hero": {
      "weekly_total_rs": 188.86,
      "week_change_pct": -7.2,
      "verdict": "Stable arrivals across primary Mandis keep the Pune kitchen basket balanced.",
      "verdict_status": "fair",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 1848.3,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 24.4,
        "day_change_rs": -0.71,
        "week_change_pct": -2.2,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Kolar steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 370,
        "retail_box_equivalent_rs": 488,
        "bulk_savings_rs": 118,
        "bulk_savings_pct": 24.2,
        "rupee_journey": {
          "farmgate_rs_kg": 15.71,
          "transit_fee_rs_kg": 2.77,
          "retail_margin_rs_kg": 5.73,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.194,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 4400.0,
        "retail_provenance": "synthetic_proxy",
        "retail_equivalent_rs_kg": 59.4,
        "day_change_rs": 0.0,
        "week_change_pct": -17.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Lasalgaon stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2200,
        "retail_box_equivalent_rs": 2970,
        "bulk_savings_rs": 770,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 37.4,
          "transit_fee_rs_kg": 6.6,
          "retail_margin_rs_kg": 14.94,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.462,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 1650.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 22.8,
        "day_change_rs": -7.0,
        "week_change_pct": 0.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Farrukhabad steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 825,
        "retail_box_equivalent_rs": 1142,
        "bulk_savings_rs": 317,
        "bulk_savings_pct": 27.8,
        "rupee_journey": {
          "farmgate_rs_kg": 14.03,
          "transit_fee_rs_kg": 2.48,
          "retail_margin_rs_kg": 6.16,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.173,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  }
};
