/**
 * Mandi Pulse - Reference Market Snapshot & Fallback Provider
 * Synchronized automatically from SQLite Warehouse (v_live_mandi_prices).
 * Generated at: 2026-09-14 07:37:09
 */

export const METRO_HUBS = [
  {
    "id": "delhi",
    "name": "Delhi NCR",
    "terminal_mandi": "Azadpur APMC",
    "district": "North Delhi",
    "lgd_code": 93
  },
  {
    "id": "mumbai",
    "name": "Mumbai MMR",
    "terminal_mandi": "Vashi (Navi Mumbai)",
    "district": "Thane",
    "lgd_code": 499
  },
  {
    "id": "bengaluru",
    "name": "Bengaluru",
    "terminal_mandi": "Yeshwanthpur APMC",
    "district": "Bengaluru Urban",
    "lgd_code": 529
  },
  {
    "id": "kolkata",
    "name": "Kolkata",
    "terminal_mandi": "Mechua Fruit & Veg Market",
    "district": "Kolkata",
    "lgd_code": 318
  },
  {
    "id": "pune",
    "name": "Pune",
    "terminal_mandi": "Gultekdi Market Yard",
    "district": "Pune",
    "lgd_code": 490
  }
];

export const REFERENCE_MARKET_DATA = {
  "delhi": {
    "metro_name": "Delhi NCR",
    "reporting_date": "10 Sep 2026",
    "terminal_mandi": "Azadpur APMC",
    "basket_hero": {
      "weekly_total_rs": 150.4,
      "week_change_pct": -19.4,
      "verdict": "Stable arrivals across primary Mandis keep the Delhi NCR kitchen basket balanced.",
      "verdict_status": "fair",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 2367.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 32.0,
        "day_change_rs": -5.13,
        "week_change_pct": -17.5,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Kolar stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 473,
        "retail_box_equivalent_rs": 640,
        "bulk_savings_rs": 167,
        "bulk_savings_pct": 26.1,
        "rupee_journey": {
          "farmgate_rs_kg": 41.65,
          "transit_fee_rs_kg": 7.35,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.473,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": -4.161,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Pimpalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 3281.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 44.6,
        "day_change_rs": 2.79,
        "week_change_pct": 9.7,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Pimpalgaon steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1640,
        "retail_box_equivalent_rs": 2230,
        "bulk_savings_rs": 590,
        "bulk_savings_pct": 26.5,
        "rupee_journey": {
          "farmgate_rs_kg": 25.5,
          "transit_fee_rs_kg": 4.5,
          "retail_margin_rs_kg": 13.94,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.656,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Pimpalgaon",
          "distance_km": 600,
          "arrival_z_score": -2.562,
          "weather_context": "Monsoon transitions across Pimpalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 1087.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 14.6,
        "day_change_rs": -10.63,
        "week_change_pct": -49.4,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Farrukhabad stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 544,
        "retail_box_equivalent_rs": 730,
        "bulk_savings_rs": 186,
        "bulk_savings_pct": 25.5,
        "rupee_journey": {
          "farmgate_rs_kg": 4.67,
          "transit_fee_rs_kg": 0.82,
          "retail_margin_rs_kg": 8.88,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.217,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": -6.433,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "mumbai": {
    "metro_name": "Mumbai MMR",
    "reporting_date": "13 Sep 2026",
    "terminal_mandi": "Vashi (Navi Mumbai)",
    "basket_hero": {
      "weekly_total_rs": 216.58,
      "week_change_pct": 32.2,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 1500.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 38.0,
        "day_change_rs": -2.0,
        "week_change_pct": -41.5,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Kolar stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 300,
        "retail_box_equivalent_rs": 760,
        "bulk_savings_rs": 460,
        "bulk_savings_pct": 60.5,
        "rupee_journey": {
          "farmgate_rs_kg": 12.75,
          "transit_fee_rs_kg": 2.25,
          "retail_margin_rs_kg": 22.82,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.158,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 5000.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 67.5,
        "day_change_rs": 20.0,
        "week_change_pct": 92.4,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Lasalgaon arrivals slumped 5.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2500,
        "retail_box_equivalent_rs": 3375,
        "bulk_savings_rs": 875,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 36.98,
          "transit_fee_rs_kg": 6.53,
          "retail_margin_rs_kg": 23.47,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.525,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": -5.044,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 1850.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 21.8,
        "day_change_rs": 1.5,
        "week_change_pct": 8.8,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Farrukhabad steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 925,
        "retail_box_equivalent_rs": 1090,
        "bulk_savings_rs": 165,
        "bulk_savings_pct": 15.1,
        "rupee_journey": {
          "farmgate_rs_kg": 15.72,
          "transit_fee_rs_kg": 2.77,
          "retail_margin_rs_kg": 3.11,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.194,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "bengaluru": {
    "metro_name": "Bengaluru",
    "reporting_date": "11 Sep 2026",
    "terminal_mandi": "Yeshwanthpur APMC",
    "basket_hero": {
      "weekly_total_rs": 152.0,
      "week_change_pct": -5.2,
      "verdict": "Stable arrivals across primary Mandis keep the Bengaluru kitchen basket balanced.",
      "verdict_status": "fair",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 2234.1,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 29.0,
        "day_change_rs": 0.23,
        "week_change_pct": 1.2,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Kolar steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 447,
        "retail_box_equivalent_rs": 580,
        "bulk_savings_rs": 133,
        "bulk_savings_pct": 22.9,
        "rupee_journey": {
          "farmgate_rs_kg": 41.65,
          "transit_fee_rs_kg": 7.35,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.335,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": -4.161,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 2500.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 34.5,
        "day_change_rs": -10.0,
        "week_change_pct": -13.7,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Lasalgaon stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1250,
        "retail_box_equivalent_rs": 1725,
        "bulk_savings_rs": 475,
        "bulk_savings_pct": 27.5,
        "rupee_journey": {
          "farmgate_rs_kg": 21.25,
          "transit_fee_rs_kg": 3.75,
          "retail_margin_rs_kg": 9.12,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.375,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 2000.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 27.0,
        "day_change_rs": 0.0,
        "week_change_pct": 0.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Farrukhabad steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1000,
        "retail_box_equivalent_rs": 1350,
        "bulk_savings_rs": 350,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 17.0,
          "transit_fee_rs_kg": 3.0,
          "retail_margin_rs_kg": 6.7,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.3,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "kolkata": {
    "metro_name": "Kolkata",
    "reporting_date": "13 Sep 2026",
    "terminal_mandi": "Mechua Fruit & Veg Market",
    "basket_hero": {
      "weekly_total_rs": 187.02,
      "week_change_pct": 40.4,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 2200.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 38.0,
        "day_change_rs": 2.0,
        "week_change_pct": 10.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Kolar steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 440,
        "retail_box_equivalent_rs": 760,
        "bulk_savings_rs": 320,
        "bulk_savings_pct": 42.1,
        "rupee_journey": {
          "farmgate_rs_kg": 18.7,
          "transit_fee_rs_kg": 3.3,
          "retail_margin_rs_kg": 15.76,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.22,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 5200.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 52.7,
        "day_change_rs": -6.0,
        "week_change_pct": 67.3,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Lasalgaon arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2600,
        "retail_box_equivalent_rs": 2636,
        "bulk_savings_rs": 36,
        "bulk_savings_pct": 1.4,
        "rupee_journey": {
          "farmgate_rs_kg": 44.2,
          "transit_fee_rs_kg": 7.8,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.52,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 2600.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 21.8,
        "day_change_rs": -22.0,
        "week_change_pct": 28.8,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1300,
        "retail_box_equivalent_rs": 1090,
        "bulk_savings_rs": 0,
        "bulk_savings_pct": 0.0,
        "rupee_journey": {
          "farmgate_rs_kg": 22.1,
          "transit_fee_rs_kg": 3.9,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.26,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "pune": {
    "metro_name": "Pune",
    "reporting_date": "13 Sep 2026",
    "terminal_mandi": "Gultekdi Market Yard",
    "basket_hero": {
      "weekly_total_rs": 222.86,
      "week_change_pct": 79.5,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 1848.3,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 24.4,
        "day_change_rs": -0.71,
        "week_change_pct": -2.2,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Kolar steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 370,
        "retail_box_equivalent_rs": 488,
        "bulk_savings_rs": 118,
        "bulk_savings_pct": 24.2,
        "rupee_journey": {
          "farmgate_rs_kg": 15.71,
          "transit_fee_rs_kg": 2.77,
          "retail_margin_rs_kg": 5.73,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.194,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 4350.0,
        "retail_provenance": "synthetic_proxy",
        "retail_equivalent_rs_kg": 58.7,
        "day_change_rs": 0.0,
        "week_change_pct": 0.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Lasalgaon steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2175,
        "retail_box_equivalent_rs": 2936,
        "bulk_savings_rs": 761,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 36.98,
          "transit_fee_rs_kg": 6.52,
          "retail_margin_rs_kg": 14.77,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.457,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 3000.0,
        "retail_provenance": "synthetic_proxy",
        "retail_equivalent_rs_kg": 40.5,
        "day_change_rs": 20.0,
        "week_change_pct": 200.0,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1500,
        "retail_box_equivalent_rs": 2025,
        "bulk_savings_rs": 525,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 25.5,
          "transit_fee_rs_kg": 4.5,
          "retail_margin_rs_kg": 10.19,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.315,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  }
};
