/**
 * Mandi Pulse - Reference Market Snapshot & Fallback Provider
 * Synchronized automatically from SQLite Warehouse (v_live_mandi_prices).
 * Generated at: 2026-09-15 12:03:12
 */

export const METRO_HUBS = [
  {
    "id": "delhi",
    "name": "Delhi NCR",
    "terminal_mandi": "Azadpur APMC",
    "district": "North Delhi",
    "lgd_code": 93
  },
  {
    "id": "mumbai",
    "name": "Mumbai MMR",
    "terminal_mandi": "Vashi (Navi Mumbai)",
    "district": "Thane",
    "lgd_code": 499
  },
  {
    "id": "bengaluru",
    "name": "Bengaluru",
    "terminal_mandi": "Yeshwanthpur APMC",
    "district": "Bengaluru Urban",
    "lgd_code": 529
  },
  {
    "id": "kolkata",
    "name": "Kolkata",
    "terminal_mandi": "Mechua Fruit & Veg Market",
    "district": "Kolkata",
    "lgd_code": 318
  },
  {
    "id": "pune",
    "name": "Pune",
    "terminal_mandi": "Gultekdi Market Yard",
    "district": "Pune",
    "lgd_code": 490
  }
];

export const REFERENCE_MARKET_DATA = {
  "delhi": {
    "metro_name": "Delhi NCR",
    "reporting_date": "14 Sep 2026",
    "terminal_mandi": "Azadpur APMC",
    "basket_hero": {
      "weekly_total_rs": 168.9,
      "week_change_pct": -0.9,
      "verdict": "Stable arrivals across primary Mandis keep the Delhi NCR kitchen basket balanced.",
      "verdict_status": "fair",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 2319.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 31.3,
        "day_change_rs": -0.48,
        "week_change_pct": -19.9,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Kolar stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 464,
        "retail_box_equivalent_rs": 626,
        "bulk_savings_rs": 162,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 27.2,
          "transit_fee_rs_kg": 4.8,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.464,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": -8.852,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 2100.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 28.6,
        "day_change_rs": -11.81,
        "week_change_pct": -30.4,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Lasalgaon stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1050,
        "retail_box_equivalent_rs": 1430,
        "bulk_savings_rs": 380,
        "bulk_savings_pct": 26.6,
        "rupee_journey": {
          "farmgate_rs_kg": 17.85,
          "transit_fee_rs_kg": 3.15,
          "retail_margin_rs_kg": 7.18,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.42,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 3000.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 40.2,
        "day_change_rs": 19.13,
        "week_change_pct": 38.2,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 6.5\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1500,
        "retail_box_equivalent_rs": 2010,
        "bulk_savings_rs": 510,
        "bulk_savings_pct": 25.4,
        "rupee_journey": {
          "farmgate_rs_kg": 5.39,
          "transit_fee_rs_kg": 0.95,
          "retail_margin_rs_kg": 33.26,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.6,
          "statutory_cess_label": "Delhi NCR APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": -6.492,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "mumbai": {
    "metro_name": "Mumbai MMR",
    "reporting_date": "15 Sep 2026",
    "terminal_mandi": "Vashi (Navi Mumbai)",
    "basket_hero": {
      "weekly_total_rs": 192.61,
      "week_change_pct": 38.6,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 750.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 39.2,
        "day_change_rs": -8.5,
        "week_change_pct": -71.3,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Kolar stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 150,
        "retail_box_equivalent_rs": 784,
        "bulk_savings_rs": 634,
        "bulk_savings_pct": 80.9,
        "rupee_journey": {
          "farmgate_rs_kg": 6.38,
          "transit_fee_rs_kg": 1.12,
          "retail_margin_rs_kg": 31.61,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.079,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 4350.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 53.9,
        "day_change_rs": -6.5,
        "week_change_pct": 64.2,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Lasalgaon arrivals slumped 3.6\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2175,
        "retail_box_equivalent_rs": 2696,
        "bulk_savings_rs": 521,
        "bulk_savings_pct": 19.3,
        "rupee_journey": {
          "farmgate_rs_kg": 36.55,
          "transit_fee_rs_kg": 6.45,
          "retail_margin_rs_kg": 10.46,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.457,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": -3.613,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 2350.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 22.8,
        "day_change_rs": 9.5,
        "week_change_pct": 67.9,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1175,
        "retail_box_equivalent_rs": 1140,
        "bulk_savings_rs": 0,
        "bulk_savings_pct": 0.0,
        "rupee_journey": {
          "farmgate_rs_kg": 19.97,
          "transit_fee_rs_kg": 3.52,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.247,
          "statutory_cess_label": "Mumbai MMR APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "bengaluru": {
    "metro_name": "Bengaluru",
    "reporting_date": "11 Sep 2026",
    "terminal_mandi": "Yeshwanthpur APMC",
    "basket_hero": {
      "weekly_total_rs": 152.0,
      "week_change_pct": -5.2,
      "verdict": "Stable arrivals across primary Mandis keep the Bengaluru kitchen basket balanced.",
      "verdict_status": "fair",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 2234.1,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 29.0,
        "day_change_rs": 0.23,
        "week_change_pct": 1.2,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Kolar steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 447,
        "retail_box_equivalent_rs": 580,
        "bulk_savings_rs": 133,
        "bulk_savings_pct": 22.9,
        "rupee_journey": {
          "farmgate_rs_kg": 41.65,
          "transit_fee_rs_kg": 7.35,
          "retail_margin_rs_kg": 1.0,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.335,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": -4.161,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 2500.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 34.5,
        "day_change_rs": -10.0,
        "week_change_pct": -13.7,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\ud83d\udfe2 Cooling Down in ~7d",
        "trend_status": "cooling",
        "advice": "Bumper inflows from Lasalgaon stabilizing corridor supply. Favorable pricing for volume buying.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1250,
        "retail_box_equivalent_rs": 1725,
        "bulk_savings_rs": 475,
        "bulk_savings_pct": 27.5,
        "rupee_journey": {
          "farmgate_rs_kg": 21.25,
          "transit_fee_rs_kg": 3.75,
          "retail_margin_rs_kg": 9.12,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.375,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 2000.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 27.0,
        "day_change_rs": 0.0,
        "week_change_pct": 0.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Farrukhabad steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1000,
        "retail_box_equivalent_rs": 1350,
        "bulk_savings_rs": 350,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 17.0,
          "transit_fee_rs_kg": 3.0,
          "retail_margin_rs_kg": 6.7,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.3,
          "statutory_cess_label": "Bengaluru APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "kolkata": {
    "metro_name": "Kolkata",
    "reporting_date": "15 Sep 2026",
    "terminal_mandi": "Mechua Fruit & Veg Market",
    "basket_hero": {
      "weekly_total_rs": 255.99,
      "week_change_pct": 49.7,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 3200.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 39.2,
        "day_change_rs": 11.0,
        "week_change_pct": 52.4,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Kolar arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 640,
        "retail_box_equivalent_rs": 784,
        "bulk_savings_rs": 144,
        "bulk_savings_pct": 18.4,
        "rupee_journey": {
          "farmgate_rs_kg": 27.2,
          "transit_fee_rs_kg": 4.8,
          "retail_margin_rs_kg": 6.87,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.32,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 5200.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 72.8,
        "day_change_rs": 0.0,
        "week_change_pct": 65.9,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Lasalgaon arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2600,
        "retail_box_equivalent_rs": 3640,
        "bulk_savings_rs": 1040,
        "bulk_savings_pct": 28.6,
        "rupee_journey": {
          "farmgate_rs_kg": 44.2,
          "transit_fee_rs_kg": 7.8,
          "retail_margin_rs_kg": 20.28,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.52,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 2700.0,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 35.6,
        "day_change_rs": 1.0,
        "week_change_pct": 32.2,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 1350,
        "retail_box_equivalent_rs": 1780,
        "bulk_savings_rs": 430,
        "bulk_savings_pct": 24.2,
        "rupee_journey": {
          "farmgate_rs_kg": 22.95,
          "transit_fee_rs_kg": 4.05,
          "retail_margin_rs_kg": 8.33,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.27,
          "statutory_cess_label": "Kolkata APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  },
  "pune": {
    "metro_name": "Pune",
    "reporting_date": "15 Sep 2026",
    "terminal_mandi": "Gultekdi Market Yard",
    "basket_hero": {
      "weekly_total_rs": 274.16,
      "week_change_pct": 49.5,
      "verdict": "The basket is up this week due to corridor arrival bottlenecks in primary production basins.",
      "verdict_status": "warning",
      "composition": "Based on weekly staple needs: 1 kg Tomato, 2 kg Onion, 2 kg Potato"
    },
    "commodities": [
      {
        "id": "tomato",
        "name": "Tomato",
        "variety": "Hybrid Red (Kolar)",
        "icon": "\ud83c\udf45",
        "wholesale_price_rs_qtl": 1848.3,
        "retail_provenance": "empirical_dca",
        "retail_equivalent_rs_kg": 24.4,
        "day_change_rs": -0.71,
        "week_change_pct": -2.2,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Kolar steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "20 kg Crate",
        "package_size_kg": 20,
        "crate_rate_rs": 370,
        "retail_box_equivalent_rs": 488,
        "bulk_savings_rs": 118,
        "bulk_savings_pct": 24.2,
        "rupee_journey": {
          "farmgate_rs_kg": 15.71,
          "transit_fee_rs_kg": 2.77,
          "retail_margin_rs_kg": 5.73,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.194,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Kolar",
          "distance_km": 400,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Kolar agricultural basin.",
          "crop_season": "Kharif Mid-Harvest"
        }
      },
      {
        "id": "onion",
        "name": "Onion",
        "variety": "Nashik Red (Lasalgaon)",
        "icon": "\ud83e\uddc5",
        "wholesale_price_rs_qtl": 4750.0,
        "retail_provenance": "synthetic_proxy",
        "retail_equivalent_rs_kg": 64.1,
        "day_change_rs": 0.0,
        "week_change_pct": 0.0,
        "status": "fair",
        "status_label": "Fair Price",
        "trend_signal": "\u26aa Stable Corridor",
        "trend_status": "stable",
        "advice": "Supply from Lasalgaon steady along the transit corridor. Stable wholesale arrivals expected.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2375,
        "retail_box_equivalent_rs": 3206,
        "bulk_savings_rs": 831,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 40.38,
          "transit_fee_rs_kg": 7.12,
          "retail_margin_rs_kg": 16.13,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.499,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Lasalgaon",
          "distance_km": 600,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Lasalgaon agricultural basin.",
          "crop_season": "Late Kharif Transition"
        }
      },
      {
        "id": "potato",
        "name": "Potato",
        "variety": "Pukhraj / Jyoti (Farrukhabad)",
        "icon": "\ud83e\udd54",
        "wholesale_price_rs_qtl": 4500.0,
        "retail_provenance": "synthetic_proxy",
        "retail_equivalent_rs_kg": 60.8,
        "day_change_rs": 25.0,
        "week_change_pct": 125.0,
        "status": "shock",
        "status_label": "Severe Spike",
        "trend_signal": "\ud83d\udd34 Spike in ~10d",
        "trend_status": "spike",
        "advice": "Farrukhabad arrivals slumped 0.0\u03c3 against seasonal averages. Procure buffer before weekend.",
        "packaging_type": "50 kg Sack",
        "package_size_kg": 50,
        "crate_rate_rs": 2250,
        "retail_box_equivalent_rs": 3038,
        "bulk_savings_rs": 788,
        "bulk_savings_pct": 25.9,
        "rupee_journey": {
          "farmgate_rs_kg": 38.25,
          "transit_fee_rs_kg": 6.75,
          "retail_margin_rs_kg": 15.28,
          "statutory_cess_pct": 2.0,
          "statutory_cess_rs_kg": 0.473,
          "statutory_cess_label": "Pune APMC Cess & Market Fees",
          "origin_mandi": "Farrukhabad",
          "distance_km": 300,
          "arrival_z_score": 0.0,
          "weather_context": "Monsoon transitions across Farrukhabad agricultural basin.",
          "crop_season": "Rabi Cold Storage Dispatches"
        }
      }
    ]
  }
};
